name: Validate PR commit messages
on: pull_request
jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -y jq
      - name: Get PR commits
        run: curl -o commits.json ${{ github.event.pull_request.commits_url }}
      - name: Validate commits
        run: |
          $GITHUB_WORKSPACE/.github/scripts/validate-commits.sh